//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAssign1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Bookings = new HashSet<Booking>();
            this.RestaurantRatings = new HashSet<RestaurantRating>();
        }

        public int RestaurantId { get; set; }

        [DisplayName("Restaurant Name")]
        public string RestaurantName { get; set; }

        [DisplayName("Restaurant Cuisine")]
        public string RestaurantCuisine { get; set; }

        [DisplayName("Restaurant Rating")]
        public Nullable<int> RestaurantRating { get; set; }

        [DisplayName("Restaurant Location")]
        public string RestaurantLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantRating> RestaurantRatings { get; set; }
    }
}
